### ISSUE TITLE
Tensorflow CUDA Compute capabilities

### ISSUE THREAD

**Issue by ofirbb** [floydhub/dockerfiles#12]
In the GPU docker files for tensorflow you use the following capabilities to setup bazel:
`ENV TF_CUDA_COMPUTE_CAPABILITIES=3.0,3.5,5.2,6.0,6.1`.

Though the `p2.xlarge` instances in AWS use the K80 which support the `3.7` compute capabilities.

Can you please explain what makes your current configuration optimized for AWS? Why not simply use `3.7` in the compute capabilities field?

Thanks.

**Comment by saiprashanths** [comment]
Good catch! Made the change, will test and release the optimized build soon.

**Comment by houqp** [comment]
Thanks @ofirbb, all new tensorflow images are now built with this optimization.
