### ISSUE TITLE
Keras backend in theano:py2 

### ISSUE THREAD

**Issue by Jiangtang** [floydhub/dockerfiles#13]
Hi, I launched a machine by:

```
floyd run --mode jupyter  --data SyccinddLDdS7p3vzcwGQ2  --env theano:py2  --gpu
```

In the notebook, I checked the Keras backend  by:

```
!cat ~/.keras/keras.json
```

It returns:

```
{
    "image_dim_ordering": "tf", 
    "epsilon": 1e-07, 
    "floatx": "float32", 
    "backend": "tensorflow"
}
```

Could you please change it to something like:

```
{
    "image_dim_ordering": "th",
    "epsilon": 1e-07,
    "floatx": "float32",
    "backend": "theano"
}
```

**Comment by ReDeiPirati** [comment]
Hi @Jiangtang,

Thanks for reporting this. It was done, [here](https://github.com/floydhub/dockerfiles/blob/master/dl/theano/theano-0.x.x.jinja#L56-L57).
