### ISSUE TITLE
Update theano

### ISSUE THREAD

**Issue by Sentient07** [floydhub/dockerfiles#14]
Hi, 
Theano 0.9 has been released. It would be great if you can upgrade the version in the docker image.

Thanks

**Comment by Sentient07** [comment]
Also, it would be great if you can update the device flag to `cuda` instead of `gpu` and `lib.cnmem` to `gpuarray.preallocate`. These correspond to the new backend. The old backend has now been deleted. 
https://hub.docker.com/r/floydhub/theano/~/dockerfile/

**Comment by Sentient07** [comment]
Thank you very much for updating the version and adding support to `libgpuarray`. I use the bleeding edge version of `floyd-cli` but I am not able to use this version of theano when i use `theano:py2` package. Could you help me out with that ? @houqp @narenst 
Thanks!

**Comment by houqp** [comment]
Hi @Sentient07 , I have already added pygpu through manual compilation: https://github.com/floydhub/dockerfiles/blob/master/dl/theano/0.9.0/Dockerfile-py3.gpu#L31.

I am still testing the new image to make sure it's working properly. If everything goes well, floydhub will make it available in two weeks I think.

**Comment by houqp** [comment]
Hi @Sentient07 , we have released a new set of chainer images. You can test it out by upgrading your floyd cli and run the experiment with `--env chainer-2.0` or `--env chainer-1.23` arguments.
