### ISSUE TITLE
Build xgboost with GPU support

### ISSUE THREAD

**Issue by saiprashanths** [floydhub/dockerfiles#35]
Have to build XGBoost [with GPU support](https://github.com/dmlc/xgboost/blob/master/doc/build.md#building-with-gpu-support) for the GPU images using the `-DUSE_CUDA=ON` flag

**Comment by ReDeiPirati** [comment]
Hi @saiprashanths, I'm closing this because it was done, [here](https://github.com/floydhub/dockerfiles/blob/master/dl/dl-base/dl-base-2.x.x.jinja#L93-L98)
