### ISSUE TITLE
Add Annoy python package

### ISSUE THREAD

**Issue by rmdort** [floydhub/dockerfiles#40]
Could you please add https://github.com/spotify/annoy to dl-base docker image? So its available across all dl experiments

Annoy is used to find word embeddings using nearest neighbours. Its quite a popular plugin for nlp tasks. Thank you so much

**Comment by rmdort** [comment]
Any update on this please.

````
pip install annoy
````

**Comment by houqp** [comment]
sorry, this issue fall through the cracks. we are rebuilding all the environments for the upcoming metrics feature release, I will make sure this is added to the list. It will take roughly 1 week to roll out.

**Comment by rmdort** [comment]
thank you 👍

**Comment by houqp** [comment]
closing this ticket since annoy has been added couple months ago.
